### ISSUE TITLE
Как установить

### ISSUE THREAD

**Issue by Vanguger** [PopcornPHP/oc-market-plugin#1]
Подскажите, как установить плагин? При входе возникает ошибка:

SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'popcornphp_market_rel_product_property' already exists (SQL: create table `popcornphp_market_rel_product_property` (`product_id` int unsigned not null, `property_id` int unsigned not null, `value_id` int unsigned not null) default character set utf8 collate utf8_unicode_ci engine = InnoDB)

**Comment by OleksandrWebLab** [comment]
@Vanguger выполните команду `php artisan plugin:refresh PopcornPHP.Market`. Команда полностью переустановит плагин, удалив всё содержимое таблиц плагина из БД, по этому сделайте backup содержимого таблиц плагина, если там есть ценная информация.

Если нет доступа к консоли - удалите плагин через админ панель. Убедитесь что в БД не осталось таблиц плагина. Загрузите исходники плагина на хостинг и перезайдите в админку, миграции выполнятся автоматически.
