### ISSUE TITLE
Ошибка установки   [Illuminate\Database\QueryException] 

### ISSUE THREAD

**Issue by c01nd01r** [PopcornPHP/oc-market-plugin#2]
Устанавливал как соседнем ишью (https://github.com/PopcornPHP/oc-market-plugin/issues/1)
* Залил файлы в plugins
* php artisan plugin:refresh PopcornPHP.Market
Ошибка: 
```sql
 [Illuminate\Database\QueryException]                                                                                
  SQLSTATE[42000]: Syntax error or access violation: 1059 Identifier name 'popcornphp_market_rel_product_property_pr  
  oduct_id_property_id_primary' is too long (SQL: alter table `popcornphp_market_rel_product_property` add primary k  
  ey `popcornphp_market_rel_product_property_product_id_property_id_primary`(`product_id`, `property_id`))

[PDOException]                                                                                                      
  SQLSTATE[42000]: Syntax error or access violation: 1059 Identifier name 'popcornphp_market_rel_product_property_pr  
  oduct_id_property_id_primary' is too long
```

**Comment by c01nd01r** [comment]
Походу нужно добавить вторым аргументом название таблицы в $table->primary() ?
https://stackoverflow.com/questions/28626906/laravel-migration-primary-or-key-identifier-name-is-too-long

**Comment by c01nd01r** [comment]
Вообще, глюков многовато. 
Нет банальной валидации полей при создании продукта. 
Если не заполнить поля связанные с ценой и нажать "Сохранить", то выскачит попап и скажет, мол ошибка в php файле, в такой-то строке.

**Comment by OleksandrWebLab** [comment]
@c01nd01r ошибка заключалась в том что MySQL не позволяет создавать длинные составные ключи
"Identifier name 'popcornphp_market_rel_product_property_product_id_property_id_primary' is too long". Исправил последним коммитом.

Проект создавался как базовый функционал для интернет-магазинов (максимум универсальности). Если у вас есть предложения по доработке - с радостью жду ваших Pull Request :)
